apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: charts/beerboard-demo
    repoURL: git@github.com:puppetlabs/cloud-strings.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: heathseals/beerboard
          tag: {{.IMAGE_TAG}}
        ingress:
          enabled: true
          annotations: 
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
           - host: {{.APP_ID}}.{{.PREVIEW_DOMAIN}}
             paths:
               - path: /
                 pathType: ImplementationSpecific
          tls: 
             - secretName: {{.APP_ID}}.{{.PREVIEW_DOMAIN}}-tls
               hosts:
                 - {{.APP_ID}}.{{.PREVIEW_DOMAIN}}
      version: v3
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
